[package]
name = "meexprox"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_yml = "0.0.10"
rust_mc_proto = "0.1.15"
uuid = "1.10.0"
log = "0.4.22"
simplelog = "0.12.2"
derivative = "2.2.0"
no_deadlocks = "1.3.2"
