host: 127.0.0.1:25565 # host to bind meexprox

talk_host: 127.0.0.1:12346 # secret host to talk with meexprox (optional)
talk_secret: qwerty123456 # secret token for talk with meexprox (optional)

servers: # verified servers (name -> ip)
  play: 127.0.0.1:12345

forced_hosts: # connect to server from connected hostname (name -> hostname) (optional)
  play: play.localhost

default_server: play # default server to connect (optional)

player_forwarding: # how to transfer player ip to connected server (velocity:PASSWORD / bungeecord / bungeeguard:PASSWORD / none)
  _: none # default player forwarding
  play: velocity:123456 # specific player forwarding