host: 127.0.0.1:25565 # host to bind meexprox

messaging: # messaging server (optional)
  enabled: true
  host: 127.0.0.1:12346 # host
  secret: qwerty123456  # secret key

servers:
  play: # server internal name
    host: sloganmc.ru:25565 # server host
    domains: 
      - _ # means that this server is default to connect players
      - play.localhost
      - mc.localhost
    forwarding: # player forwarding
      enabled: false
      type: velocity
      secret: "123456"

default_forwarding: # player forwarding to use when you connecting by ip
  enabled: false # disable player forwarding means that you dont need to transfer player's ip and other info to this server
  # type: velocity
  # secret: "123456"

incoming_forwarding: # player forwarding for incoming connections
  enabled: false
  # type: velocity
  # secret: "123456"

# player forwarding types: 
# - velocity (or "modern" in Velocity config) (secret is required)
# - bungeecord (or "legacy" in Velocity config) (secret is optional)
# - meexprox (open-source protocol) (secret is required)
# - none (enabled: false)